### DESTINOS
###
### CREATE
### Cidades (Destinos) no banco: São Luís, AlcÂntara, Barreirinhas, Carolina, Tutóia;
POST http://localhost:3000/api/destinos
Content-Type: application/json

{
    "nome": "São Luís do Maranhão",
    "descricao": "Capital do estado e uma das primeiras cidades fundadas no Brasil, é ,em diversos aspectos, o polo central para os visitantes que chegam no estado",
    "localizacao": {"latitude": "-2.53073","longitude": "-44.3068"},
    "imagem": "https://www.viagensecaminhos.com/wp-content/uploads/2016/11/vista-aerea-centro-historico-sao-luis.jpg",
    "slug": "sao-luis"
}
###
POST http://localhost:3000/api/destinos
Content-Type: application/json

{
    "nome": "Alcântara",
    "descricao": "Uma das cidades históricas mais antigas do Maranhão, fundada como Tapuytapera possui ruínas históricas de valor único bem como atrativos naturais",
    "localizacao": {"latitude": "-2.4110","longitude": "-44.4188"},
    "imagem": "https://www.atins.me/wp-content/uploads/2011/09/Alcantara-02_952x476.jpg",
    "slug": "alcantara"
}
###
POST http://localhost:3000/api/destinos
Content-Type: application/json

{
    "nome": "Barreirinhas",
    "descricao": "Uma das portas de entrada para o Parque Nacional dos Lençóis Maranhenses, tem localização privilegiada para essa área bem como pontos de interesse tal como o Rio Preguiças",
    "localizacao": {"latitude": "-2.720550","longitude": "-42.837070"},
    "imagem": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fguia.melhoresdestinos.com.br%2Fbarreirinhas-220-6113-l.html&psig=AOvVaw0PIbhIw89O8p4TkDriqoUF&ust=1723202372734000&source=images&cd=vfe&opi=89978449&ved=0CA8QjRxqFwoTCLi6xM2l5YcDFQAAAAAdAAAAABAT",
    "slug": "barreirinhas"
}
###
POST http://localhost:3000/api/destinos
Content-Type: application/json

{
    "nome": "Carolina",
    "descricao": "Localizada na região sudoeste do Maranhão, Carolina é uma base para todo visitante que planeja fazer turismo pela Chapada das Mesas e também possui afamadas cachoeiras",
    "localizacao": {"latitude": "-7.3317","longitude": "-47.4757"},
    "imagem": "https://www.penaestrada.blog.br/wp-content/uploads/2020/08/chapada-das-mesas-95.jpg",
    "slug": "carolina"
}
###
POST http://localhost:3000/api/destinos
Content-Type: application/json

{
    "nome": "Tutoia",
    "descricao": "Localizada na parte final do Baixo Parnaíba, Tutóia figura, juntamente com Araioses, como um dos pontos de acesso para a região do Delta do Parnaíba",
    "localizacao": {"latitude": "-2.7611","longitude": "-42.2785"},
    "imagem": "https://i.pinimg.com/originals/e7/c4/df/e7c4df1848adc62f4278d76a1349216f.jpg",
    "slug": "tutoia"
}


### GET ALL
GET http://localhost:3000/api/destinos

### GET BY ID destinos/<id>
GET http://localhost:3000/api/destinos/66af1bf85a69e72ade6e6dce 

### DELETE destinos/<id>
DELETE  http://localhost:3000/api/destinos/66af1bf85a69e72ade6e6dce 

### UPDATE destinos<id>
PUT http://localhost:3000/api/destinos/66af159661e877348fde3f7f
Content-Type: application/json

{
    "nome": "Alcântara",
    "descricao": "Uma das cidades históricas mais antigas do Maranhão, fundada como Tapuytapera possui ruínas históricas de valor único bem como atrativos naturais",
    "localizacao": {"latitude": "-2.4110","longitude": "-44.4187"},
    "imagem": "https://www.atins.me/wp-content/uploads/2011/09/Alcantara-02_952x476.jpg",
    "slug": "cidade-3"
}

### ATRATIVOS 
### 
### CREATE
### Atrações criadas no banco: Ruínas da Igreja de São Matias, Forte São Antônio da Barra de São Luís
### Atrações que faltam: Teatro Arthur Azevedo, Museu Histórico e Artístico do Maranhão (MHAM), Complexo Cultural da RFFSA - Estação João Pessoa, 
### Casa do Maranhão, Catedral Metropolitana de Nossa Senhora da Vitória, Convento das Mercês
## Ecoturismo na Chapada das Mesas, Ecoturismo no Delta do Parnaíba
POST http://localhost:3000/api/atrativos
Content-Type: application/json

{
    "nome": "Ruínas da Igreja de São Matias",
    "tipo": "Igreja",
    "sobre": "As ruínas da Igreja Matriz de São Matias encontram-se na região central de Alcântara, compondo um conjunto arquitetônico com outros importantes monumentos da cidade. A igreja é um símbolo muito importante, pois foi a primeira paróquia. Durante a ocupação portuguesa fez parte do conjunto simbólico que marcou a presença desse povo naquela região e das edificações mais significativas, sendo a área da Matriz considerada o coração da Vila de Santo Antônio de Alcântara. Em torno do século XIX já começava a entrar em ruínas, hoje ainda se encontra algumas de suas paredes levantadas.",
    "localizacao": {"latitude": "-2.40865","longitude": "-44.41719"},
    "dicas": "Pela localização central é um ótimo local para dar o pontapé inicial no tour por Alcântara e ao mesmo tempo apreciar a história do Marahão, além de ser excelente para fotografias",
    "imagem": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRy2tYqjVzTjwY-yexdQ0V_R0tBU9bTDGE73g&s",
    "destino": "66af9cff7a3225eb7a6f6a83",
    "slug": "ruinas-sao-matias"
}
###
POST http://localhost:3000/api/atrativos/
Content-Type: application/json

{
    "nome": "Forte Santo Antônio da Barra de São Luís",
    "tipo": "Museus",
    "sobre": "Localizado na praia da Ponta d’Areia, este forte tem uma história que remonta a séculos atrás, sendo tombado pelo IPHAN (Instituto do Patrimônio Histórico e Artístico Nacional) em 1975. O local preserva grande parte sua arquitetura original e de seu valor histórico. Hoje, o Forte de Santo Antônio da Barra é muito mais do que um monumento histórico.Ele se transformou em um espaço cultural dinâmico que mergulha os visitantes nas tradições e na rica herança maranhense. Desde 2012, o local abriga o Museu de Embarcações Tradicionais Maranhenses, um memorial sobre a história do forte e o Museu da Imagem e Som, tornando-se um destino turístico completo",
    "localizacao": {"latitude": "-2.50536","longitude": "-44.317779"},
    "dicas": "Exposições fotográficas, saraus e outros projetos de conhecimento e entretenimento são constantemente promovidos por lá!",
    "imagem": "https://turismosaoluis.com.br/wp-content/uploads/2023/10/Espigao_220823_BM-46-1024x683.jpg.webp",
    "destino": "66af9cfa7a3225eb7a6f6a81",
    "slug": "forte-santo-antonio-slz"
}
### GET ALL
GET http://localhost:3000/api/atrativos

### GET BY ID destinos/<id>
GET http://localhost:3000/api/atrativos/

### DELETE destinos/<id>
DELETE http://localhost:3000/api/atrativos/

### UPDATE destinos<id>
PUT http://localhost:3000/api/atrativos/66af2086b5cc2ff2822ae91b
Content-Type: application/json

{
    "nome": "Forte Santo Antônio da Barra de São Luís",
    "tipo": "Museu",
    "sobre": "Localizado na praia da Ponta d’Areia, este forte tem uma história que remonta a séculos atrás, sendo tombado pelo IPHAN (Instituto do Patrimônio Histórico e Artístico Nacional) em 1975. O local preserva grande parte sua arquitetura original e de seu valor histórico. Hoje, o Forte de Santo Antônio da Barra é muito mais do que um monumento histórico.Ele se transformou em um espaço cultural dinâmico que mergulha os visitantes nas tradições e na rica herança maranhense. Desde 2012, o local abriga o Museu de Embarcações Tradicionais Maranhenses, um memorial sobre a história do forte e o Museu da Imagem e Som, tornando-se um destino turístico completo",
    "localizacao": {"latitude": "-2.50535","longitude": "-44.317778"},
    "dicas": "Exposições fotográficas, saraus e outros projetos de conhecimento e entretenimento são constantemente promovidos por lá!",
    "imagem": "https://turismosaoluis.com.br/wp-content/uploads/2023/10/Espigao_220823_BM-46-1024x683.jpg.webp",
    "destino": "66af132cab302cd41392b13e"
}